
@url_dev=http://localhost:3066/v1/api/

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json

{
  "name": "abcc",
  "email": "abshssharaaddaah@example.com",
  "password": "123456"
}
